v5t11.anlage=show

v5t11.host=localhost

v5t11.db.host=${v5t11.host}
v5t11.db.port=31432

v5t11.kafka.host=${v5t11.host}
v5t11.kafka.port=31092

v5t11.mqtt.host=${v5t11.host}
v5t11.mqtt.port=31883

v5t11.web.host=${v5t11.host}
v5t11.status/web/url=http://${v5t11.web.host}:31080
v5t11.status/mp-rest/url=http://${v5t11.web.host}:31080/rs

v5t11.parcours.host=${v5t11.host}
v5t11.parcours/mp-rest/url=http://${v5t11.parcours.host}:31180

v5t11.fahrzeuge.host=${v5t11.host}
v5t11.fahrzeuge/web/url=http://${v5t11.fahrzeuge.host}:31280
v5t11.fahrzeuge/mp-rest/url=http://${v5t11.fahrzeuge.host}:31280/rs
%dev.v5t11.fahrzeuge/init-dir=fahrzeuge

v5t11.leitstand.host=${v5t11.host}
v5t11.leitstand/web/url=http://${v5t11.leitstand.host}:31380

