mv ./src/main/webapp/view/compProg.xhtml               ./src/main/webapp/view/bausteinProgrammierung.xhtml
mv ./src/main/webapp/view/compProg_BMMiba3.xhtml       ./src/main/webapp/view/bausteinProgrammierung_BMMiba3.xhtml
mv ./src/main/webapp/view/compProg_closeProgMode.xhtml ./src/main/webapp/view/bausteinProgrammierung_closeProgMode.xhtml
mv ./src/main/webapp/view/compProg_HEBM8.xhtml         ./src/main/webapp/view/bausteinProgrammierung_HEBM8.xhtml
mv ./src/main/webapp/view/compProg_Muet8i.xhtml        ./src/main/webapp/view/bausteinProgrammierung_Muet8i.xhtml
mv ./src/main/webapp/view/compProg_Muet8k.xhtml        ./src/main/webapp/view/bausteinProgrammierung_Muet8k.xhtml
mv ./src/main/webapp/view/compProg_openProgMode.xhtml  ./src/main/webapp/view/bausteinProgrammierung_openProgMode.xhtml
mv ./src/main/webapp/view/compProg_SD8.xhtml           ./src/main/webapp/view/bausteinProgrammierung_SD8.xhtml
mv ./src/main/webapp/view/compProg_STRFD1.xhtml        ./src/main/webapp/view/bausteinProgrammierung_STRFD1.xhtml
mv ./src/main/webapp/view/compProg_SXBM1.xhtml         ./src/main/webapp/view/bausteinProgrammierung_SXBM1.xhtml
mv ./src/main/webapp/view/compProg_SXSD1.xhtml         ./src/main/webapp/view/bausteinProgrammierung_SXSD1.xhtml
mv ./src/main/webapp/view/compProg_WDMiba.xhtml        ./src/main/webapp/view/bausteinProgrammierung_WDMiba.xhtml
mv ./src/main/webapp/view/compProg_WDMiba3.xhtml       ./src/main/webapp/view/bausteinProgrammierung_WDMiba3.xhtml
mv ./src/main/webapp/WEB-INF/templates/compProg.xhtml  ./src/main/webapp/WEB-INF/templates/bausteinProgrammierung.xhtml
