apiVersion: apps/v1
kind: Deployment
metadata:
  name: v5t11-mqtt
spec:
  selector:
    matchLabels:
      app: v5t11-mqtt
  template:
    metadata:
      labels:
        app: v5t11-mqtt
    spec:
      containers:
      - name: v5t11-mqtt
        image: eclipse-mosquitto:1.6.12
        ports:
        - containerPort: 1883
          name: mqtt
---
apiVersion: v1
kind: Service
metadata:
  name: v5t11-mqtt
spec:
  selector:
    app: v5t11-mqtt
  type: NodePort
  ports:
  - port: 1883
    name: mqtt
    targetPort: mqtt
    nodePort: 31883
