version: '3.7'
services:
  redpanda:
    # NOTE: Use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --set redpanda.empty_seed_starts_cluster=false
      - --seeds "redpanda-1:33145"
      - --kafka-addr
      - CLUSTERIP://0.0.0.0:9092,NODEPORT://0.0.0.0:31092
      - --advertise-kafka-addr
      - CLUSTERIP://redpanda:9092,NODEPORT://localhost:31092
      - --pandaproxy-addr
      - CLUSTERIP://0.0.0.0:8082,NODEPORT://0.0.0.0:31082
      - --advertise-pandaproxy-addr
      - CLUSTERIP://redpanda:8082,NODEPORT://localhost:31082
      - --advertise-rpc-addr redpanda-1:33145
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 31082:31082
      - 31092:31092